/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMailRouteImport } from './routes/_app.mail'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppDealsRouteImport } from './routes/_app.deals'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppVendorsIndexRouteImport } from './routes/_app.vendors.index'
import { Route as AppTasksIndexRouteImport } from './routes/_app.tasks.index'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app.sales-orders.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppQuotesIndexRouteImport } from './routes/_app.quotes.index'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app.purchase-orders.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app.meetings.index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app.leads.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppDealsIndexRouteImport } from './routes/_app.deals.index'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppCallsIndexRouteImport } from './routes/_app.calls.index'
import { Route as AppAccountsIndexRouteImport } from './routes/_app.accounts.index'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth.reset-password/$token'
import { Route as AppTasksCreateRouteImport } from './routes/_app.tasks.create'
import { Route as AppTasksIdRouteImport } from './routes/_app.tasks.$id'
import { Route as AppLeadsCreateRouteImport } from './routes/_app.leads.create'
import { Route as AppLeadsIdRouteImport } from './routes/_app.leads.$id'
import { Route as AppDealsCreateRouteImport } from './routes/_app.deals.create'
import { Route as AppDealsIdRouteImport } from './routes/_app.deals.$id'
import { Route as AppContactsCreateRouteImport } from './routes/_app.contacts.create'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppAccountsCreateRouteImport } from './routes/_app.accounts.create'
import { Route as AppAccountsIdRouteImport } from './routes/_app.accounts.$id'
import { Route as AppTasksEditIdRouteImport } from './routes/_app.tasks.edit.$id'
import { Route as AppLeadsEditIdRouteImport } from './routes/_app.leads.edit.$id'
import { Route as AppDealsEditIdRouteImport } from './routes/_app.deals.edit.$id'
import { Route as AppContactsEditIdRouteImport } from './routes/_app.contacts.edit.$id'
import { Route as AppAccountsEditIdRouteImport } from './routes/_app.accounts.edit.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMailRoute = AppMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/sales-orders/',
  path: '/sales-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsIndexRoute = AppCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppTasksCreateRoute = AppTasksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppLeadsCreateRoute = AppLeadsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppDealsCreateRoute = AppDealsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppContactsCreateRoute = AppContactsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppAccountsCreateRoute = AppAccountsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppTasksEditIdRoute = AppTasksEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppLeadsEditIdRoute = AppLeadsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppDealsEditIdRoute = AppDealsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppContactsEditIdRoute = AppContactsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppAccountsEditIdRoute = AppAccountsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/accounts': typeof AppAccountsRouteWithChildren
  '/activities': typeof AppActivitiesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/deals': typeof AppDealsRouteWithChildren
  '/leads': typeof AppLeadsRouteWithChildren
  '/mail': typeof AppMailRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/accounts/create': typeof AppAccountsCreateRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/create': typeof AppContactsCreateRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/deals/create': typeof AppDealsCreateRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/leads/create': typeof AppLeadsCreateRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/tasks/create': typeof AppTasksCreateRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/calls/': typeof AppCallsIndexRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/cases/': typeof AppCasesIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/vendors/': typeof AppVendorsIndexRoute
  '/accounts/edit/$id': typeof AppAccountsEditIdRoute
  '/contacts/edit/$id': typeof AppContactsEditIdRoute
  '/deals/edit/$id': typeof AppDealsEditIdRoute
  '/leads/edit/$id': typeof AppLeadsEditIdRoute
  '/tasks/edit/$id': typeof AppTasksEditIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/activities': typeof AppActivitiesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/mail': typeof AppMailRoute
  '/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/accounts/create': typeof AppAccountsCreateRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/create': typeof AppContactsCreateRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/deals/create': typeof AppDealsCreateRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/leads/create': typeof AppLeadsCreateRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/tasks/create': typeof AppTasksCreateRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/calls': typeof AppCallsIndexRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/cases': typeof AppCasesIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales-orders': typeof AppSalesOrdersIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/vendors': typeof AppVendorsIndexRoute
  '/accounts/edit/$id': typeof AppAccountsEditIdRoute
  '/contacts/edit/$id': typeof AppContactsEditIdRoute
  '/deals/edit/$id': typeof AppDealsEditIdRoute
  '/leads/edit/$id': typeof AppLeadsEditIdRoute
  '/tasks/edit/$id': typeof AppTasksEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/deals': typeof AppDealsRouteWithChildren
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/mail': typeof AppMailRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/accounts/create': typeof AppAccountsCreateRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/contacts/create': typeof AppContactsCreateRoute
  '/_app/deals/$id': typeof AppDealsIdRoute
  '/_app/deals/create': typeof AppDealsCreateRoute
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/leads/create': typeof AppLeadsCreateRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
  '/_app/tasks/create': typeof AppTasksCreateRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/calls/': typeof AppCallsIndexRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/vendors/': typeof AppVendorsIndexRoute
  '/_app/accounts/edit/$id': typeof AppAccountsEditIdRoute
  '/_app/contacts/edit/$id': typeof AppContactsEditIdRoute
  '/_app/deals/edit/$id': typeof AppDealsEditIdRoute
  '/_app/leads/edit/$id': typeof AppLeadsEditIdRoute
  '/_app/tasks/edit/$id': typeof AppTasksEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/activities'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/contacts'
    | '/deals'
    | '/leads'
    | '/mail'
    | '/settings'
    | '/tasks'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/accounts/$id'
    | '/accounts/create'
    | '/contacts/$id'
    | '/contacts/create'
    | '/deals/$id'
    | '/deals/create'
    | '/leads/$id'
    | '/leads/create'
    | '/tasks/$id'
    | '/tasks/create'
    | '/auth/reset-password/$token'
    | '/accounts/'
    | '/calls/'
    | '/campaigns/'
    | '/cases/'
    | '/contacts/'
    | '/deals/'
    | '/invoices/'
    | '/leads/'
    | '/meetings/'
    | '/products/'
    | '/purchase-orders/'
    | '/quotes/'
    | '/reports/'
    | '/sales-orders/'
    | '/tasks/'
    | '/vendors/'
    | '/accounts/edit/$id'
    | '/contacts/edit/$id'
    | '/deals/edit/$id'
    | '/leads/edit/$id'
    | '/tasks/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activities'
    | '/analytics'
    | '/calendar'
    | '/chat'
    | '/mail'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/accounts/$id'
    | '/accounts/create'
    | '/contacts/$id'
    | '/contacts/create'
    | '/deals/$id'
    | '/deals/create'
    | '/leads/$id'
    | '/leads/create'
    | '/tasks/$id'
    | '/tasks/create'
    | '/auth/reset-password/$token'
    | '/accounts'
    | '/calls'
    | '/campaigns'
    | '/cases'
    | '/contacts'
    | '/deals'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/products'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/sales-orders'
    | '/tasks'
    | '/vendors'
    | '/accounts/edit/$id'
    | '/contacts/edit/$id'
    | '/deals/edit/$id'
    | '/leads/edit/$id'
    | '/tasks/edit/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/accounts'
    | '/_app/activities'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/chat'
    | '/_app/contacts'
    | '/_app/deals'
    | '/_app/leads'
    | '/_app/mail'
    | '/_app/settings'
    | '/_app/tasks'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/_app/'
    | '/_app/accounts/$id'
    | '/_app/accounts/create'
    | '/_app/contacts/$id'
    | '/_app/contacts/create'
    | '/_app/deals/$id'
    | '/_app/deals/create'
    | '/_app/leads/$id'
    | '/_app/leads/create'
    | '/_app/tasks/$id'
    | '/_app/tasks/create'
    | '/auth/reset-password/$token'
    | '/_app/accounts/'
    | '/_app/calls/'
    | '/_app/campaigns/'
    | '/_app/cases/'
    | '/_app/contacts/'
    | '/_app/deals/'
    | '/_app/invoices/'
    | '/_app/leads/'
    | '/_app/meetings/'
    | '/_app/products/'
    | '/_app/purchase-orders/'
    | '/_app/quotes/'
    | '/_app/reports/'
    | '/_app/sales-orders/'
    | '/_app/tasks/'
    | '/_app/vendors/'
    | '/_app/accounts/edit/$id'
    | '/_app/contacts/edit/$id'
    | '/_app/deals/edit/$id'
    | '/_app/leads/edit/$id'
    | '/_app/tasks/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mail': {
      id: '/_app/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AppMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/': {
      id: '/_app/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/sales-orders/': {
      id: '/_app/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/': {
      id: '/_app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/': {
      id: '/_app/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof AppCallsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/tasks/create': {
      id: '/_app/tasks/create'
      path: '/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof AppTasksCreateRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/leads/create': {
      id: '/_app/leads/create'
      path: '/create'
      fullPath: '/leads/create'
      preLoaderRoute: typeof AppLeadsCreateRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/deals/create': {
      id: '/_app/deals/create'
      path: '/create'
      fullPath: '/deals/create'
      preLoaderRoute: typeof AppDealsCreateRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/deals/$id': {
      id: '/_app/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/contacts/create': {
      id: '/_app/contacts/create'
      path: '/create'
      fullPath: '/contacts/create'
      preLoaderRoute: typeof AppContactsCreateRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/accounts/create': {
      id: '/_app/accounts/create'
      path: '/create'
      fullPath: '/accounts/create'
      preLoaderRoute: typeof AppAccountsCreateRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/tasks/edit/$id': {
      id: '/_app/tasks/edit/$id'
      path: '/edit/$id'
      fullPath: '/tasks/edit/$id'
      preLoaderRoute: typeof AppTasksEditIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/leads/edit/$id': {
      id: '/_app/leads/edit/$id'
      path: '/edit/$id'
      fullPath: '/leads/edit/$id'
      preLoaderRoute: typeof AppLeadsEditIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/deals/edit/$id': {
      id: '/_app/deals/edit/$id'
      path: '/edit/$id'
      fullPath: '/deals/edit/$id'
      preLoaderRoute: typeof AppDealsEditIdRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/contacts/edit/$id': {
      id: '/_app/contacts/edit/$id'
      path: '/edit/$id'
      fullPath: '/contacts/edit/$id'
      preLoaderRoute: typeof AppContactsEditIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/accounts/edit/$id': {
      id: '/_app/accounts/edit/$id'
      path: '/edit/$id'
      fullPath: '/accounts/edit/$id'
      preLoaderRoute: typeof AppAccountsEditIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsIdRoute: typeof AppAccountsIdRoute
  AppAccountsCreateRoute: typeof AppAccountsCreateRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppAccountsEditIdRoute: typeof AppAccountsEditIdRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsIdRoute: AppAccountsIdRoute,
  AppAccountsCreateRoute: AppAccountsCreateRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppAccountsEditIdRoute: AppAccountsEditIdRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRoute
  AppContactsCreateRoute: typeof AppContactsCreateRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppContactsEditIdRoute: typeof AppContactsEditIdRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRoute,
  AppContactsCreateRoute: AppContactsCreateRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppContactsEditIdRoute: AppContactsEditIdRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppDealsRouteChildren {
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppDealsCreateRoute: typeof AppDealsCreateRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
  AppDealsEditIdRoute: typeof AppDealsEditIdRoute
}

const AppDealsRouteChildren: AppDealsRouteChildren = {
  AppDealsIdRoute: AppDealsIdRoute,
  AppDealsCreateRoute: AppDealsCreateRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
  AppDealsEditIdRoute: AppDealsEditIdRoute,
}

const AppDealsRouteWithChildren = AppDealsRoute._addFileChildren(
  AppDealsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppLeadsCreateRoute: typeof AppLeadsCreateRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppLeadsEditIdRoute: typeof AppLeadsEditIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppLeadsCreateRoute: AppLeadsCreateRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppLeadsEditIdRoute: AppLeadsEditIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksIdRoute: typeof AppTasksIdRoute
  AppTasksCreateRoute: typeof AppTasksCreateRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppTasksEditIdRoute: typeof AppTasksEditIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksIdRoute: AppTasksIdRoute,
  AppTasksCreateRoute: AppTasksCreateRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppTasksEditIdRoute: AppTasksEditIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppDealsRoute: typeof AppDealsRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMailRoute: typeof AppMailRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCallsIndexRoute: typeof AppCallsIndexRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppActivitiesRoute: AppActivitiesRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppDealsRoute: AppDealsRouteWithChildren,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMailRoute: AppMailRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCallsIndexRoute: AppCallsIndexRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
